import 'package:flutter/material.dart';
import 'package:ai_assistant/tools/models/tool_models.dart';

class ToolRegistry {
  ToolRegistry._();

  static const List<ToolDefinition> all = <ToolDefinition>[
    ToolDefinition(
      id: 'vn_lottery',
      name: 'Xổ số',
      description: 'Tra kết quả xổ số Việt Nam theo vùng, ngày và tỉnh.',
      category: ToolCategory.vietnam,
      icon: Icons.confirmation_number_rounded,
      keywords: <String>['xổ số', 'sổ số', 'sổ xố', 'xsmb', 'xsmn', 'xsmt', 'kết quả xổ số'],
      examples: <String>['Xổ số miền Bắc hôm nay', 'Kết quả XSMB hôm qua'],
      availability: ToolAvailability.partial,
    ),
    ToolDefinition(
      id: 'lunar_calendar',
      name: 'Lịch âm',
      description: 'Xem âm lịch, can chi và chuyển đổi ngày dương sang âm.',
      category: ToolCategory.vietnam,
      icon: Icons.calendar_month_rounded,
      keywords: <String>['lịch âm', 'âm lịch', 'ngày âm', 'can chi'],
      examples: <String>['Hôm nay âm lịch ngày bao nhiêu?', 'Âm lịch hôm nay'],
      requiresInternet: false,
    ),
    ToolDefinition(
      id: 'vn_area_code',
      name: 'Mã vùng điện thoại',
      description: 'Tra cứu mã vùng điện thoại cố định tại Việt Nam.',
      category: ToolCategory.vietnam,
      icon: Icons.phone_in_talk_rounded,
      keywords: <String>['mã vùng', 'đầu số cố định', 'area code'],
      examples: <String>['Mã vùng Hà Nội', '0236 là tỉnh nào?'],
      requiresInternet: false,
    ),
    ToolDefinition(
      id: 'vn_carrier_lookup',
      name: 'Tra nhà mạng',
      description: 'Nhận diện nhà mạng theo đầu số; có cảnh báo chuyển mạng giữ số.',
      category: ToolCategory.vietnam,
      icon: Icons.sim_card_rounded,
      keywords: <String>['nhà mạng', 'mạng gì', 'đầu số', 'viettel', 'vinaphone', 'mobifone'],
      examples: <String>['Số 0912 là mạng gì?', 'Đầu số 098 thuộc mạng nào?'],
      requiresInternet: false,
    ),
    ToolDefinition(
      id: 'vn_plate_lookup',
      name: 'Tra biển số xe',
      description: 'Tra cứu mã biển số tỉnh/thành và giải thích nhóm mã cơ bản.',
      category: ToolCategory.vietnam,
      icon: Icons.directions_car_filled_rounded,
      keywords: <String>['biển số', 'biển xe', 'mã biển'],
      examples: <String>['Biển 30A ở đâu?', 'Biển số 51F là tỉnh nào?'],
      requiresInternet: false,
    ),
    ToolDefinition(
      id: 'gold_price',
      name: 'Giá vàng',
      description: 'Tra giá vàng SJC từ nguồn công khai; hỗ trợ bridge dự phòng.',
      category: ToolCategory.finance,
      icon: Icons.workspace_premium_rounded,
      keywords: <String>['giá vàng', 'vàng sjc', 'vàng 9999', 'vàng nhẫn'],
      examples: <String>['Giá vàng SJC hôm nay', 'Vàng 9999 bao nhiêu?'],
      availability: ToolAvailability.partial,
    ),
    ToolDefinition(
      id: 'fx_rate',
      name: 'Tỷ giá ngoại tệ',
      description: 'Tỷ giá tham chiếu quốc tế và VND từ Frankfurter.',
      category: ToolCategory.finance,
      icon: Icons.currency_exchange_rounded,
      keywords: <String>['tỷ giá', 'usd', 'eur', 'jpy', 'cny', 'ngoại tệ'],
      examples: <String>['Tỷ giá USD hôm nay', 'EUR sang VND'],
    ),
    ToolDefinition(
      id: 'vn_bank_interest',
      name: 'Lãi suất ngân hàng',
      description: 'Tra lãi suất tiết kiệm qua Realtime Bridge đã cấu hình.',
      category: ToolCategory.finance,
      icon: Icons.account_balance_rounded,
      keywords: <String>['lãi suất', 'gửi tiết kiệm', 'vietcombank', 'agribank', 'bidv'],
      examples: <String>['Lãi suất Vietcombank 12 tháng'],
      availability: ToolAvailability.needsConfiguration,
    ),
    ToolDefinition(
      id: 'vn_fuel_price',
      name: 'Giá xăng dầu',
      description: 'Tra kỳ điều chỉnh và giá xăng dầu qua nguồn/bridge được cấu hình.',
      category: ToolCategory.finance,
      icon: Icons.local_gas_station_rounded,
      keywords: <String>['giá xăng', 'xăng ron95', 'e5 ron92', 'diesel', 'giá dầu'],
      examples: <String>['Giá xăng RON95 hôm nay'],
      availability: ToolAvailability.needsConfiguration,
    ),
    ToolDefinition(
      id: 'vn_market_index',
      name: 'Chứng khoán VN-Index',
      description: 'VNINDEX, HNXINDEX, UPCOM qua bridge dữ liệu thị trường.',
      category: ToolCategory.finance,
      icon: Icons.show_chart_rounded,
      keywords: <String>['vnindex', 'hnxindex', 'upcom', 'chứng khoán việt nam'],
      examples: <String>['VNIndex hôm nay thế nào?'],
      availability: ToolAvailability.needsConfiguration,
    ),
    ToolDefinition(
      id: 'stock_lookup',
      name: 'Tra mã cổ phiếu',
      description: 'Tra mã cổ phiếu và dữ liệu giá qua bridge thị trường.',
      category: ToolCategory.finance,
      icon: Icons.query_stats_rounded,
      keywords: <String>['cổ phiếu', 'mã fpt', 'mã vnm', 'giá cổ phiếu', 'ticker'],
      examples: <String>['Cổ phiếu FPT hôm nay', 'Giá VNM'],
      availability: ToolAvailability.needsConfiguration,
    ),
    ToolDefinition(
      id: 'crypto_price',
      name: 'Giá Crypto',
      description: 'Giá và biến động 24h từ public market-data API của Binance.',
      category: ToolCategory.market,
      icon: Icons.currency_bitcoin_rounded,
      keywords: <String>['bitcoin', 'btc', 'ethereum', 'eth', 'bnb', 'solana', 'sol', 'crypto'],
      examples: <String>['Bitcoin đang bao nhiêu?', 'ETH hôm nay tăng hay giảm?'],
    ),
    ToolDefinition(
      id: 'crypto_sentiment',
      name: 'Tâm lý thị trường Crypto',
      description: 'Chỉ số Fear & Greed của thị trường crypto.',
      category: ToolCategory.market,
      icon: Icons.psychology_alt_rounded,
      keywords: <String>['fear greed', 'sợ hãi tham lam', 'tâm lý crypto', 'tâm lý thị trường crypto'],
      examples: <String>['Fear and Greed hôm nay', 'Tâm lý crypto hiện tại'],
      availability: ToolAvailability.partial,
    ),
    ToolDefinition(
      id: 'currency_converter',
      name: 'Quy đổi tiền tệ',
      description: 'Quy đổi nhanh giữa VND, USD, EUR, JPY, CNY và nhiều đồng tiền.',
      category: ToolCategory.market,
      icon: Icons.paid_rounded,
      keywords: <String>['đổi tiền', 'quy đổi', 'sang vnd', 'sang usd', 'sang cny'],
      examples: <String>['100 USD bằng bao nhiêu VND?', '5 triệu VND sang CNY'],
    ),
    ToolDefinition(
      id: 'global_market_index',
      name: 'Chỉ số chứng khoán thế giới',
      description: 'S&P 500, Nasdaq, Dow Jones và các chỉ số toàn cầu qua bridge.',
      category: ToolCategory.market,
      icon: Icons.public_rounded,
      keywords: <String>['s&p 500', 'sp500', 'nasdaq', 'dow jones', 'nikkei', 'hang seng'],
      examples: <String>['Nasdaq hôm nay', 'S&P 500 hiện tại'],
      availability: ToolAvailability.needsConfiguration,
    ),
    ToolDefinition(
      id: 'commodity_price',
      name: 'Giá hàng hóa thế giới',
      description: 'Dầu WTI, Brent, bạc, đồng, cà phê qua bridge dữ liệu hàng hóa.',
      category: ToolCategory.market,
      icon: Icons.inventory_2_rounded,
      keywords: <String>['dầu wti', 'brent', 'giá bạc', 'giá đồng', 'cà phê thế giới', 'hàng hóa'],
      examples: <String>['Giá dầu WTI', 'Giá bạc thế giới'],
      availability: ToolAvailability.needsConfiguration,
    ),
    ToolDefinition(
      id: 'news_latest',
      name: 'Tin tức nóng',
      description: 'Đọc nhanh các tin mới nhất từ RSS chính thức của VnExpress.',
      category: ToolCategory.newsEnvironment,
      icon: Icons.newspaper_rounded,
      keywords: <String>['tin tức', 'tin mới', 'tin nóng', 'có gì mới', 'thời sự'],
      examples: <String>['Tin nóng hôm nay', 'Có tin gì mới?'],
    ),
    ToolDefinition(
      id: 'realtime_info',
      name: 'Realtime Info',
      description: 'Router tổng hợp để chọn công cụ phù hợp cho câu hỏi thời gian thực.',
      category: ToolCategory.newsEnvironment,
      icon: Icons.travel_explore_rounded,
      keywords: <String>['realtime', 'hiện tại', 'mới nhất', 'hôm nay'],
      examples: <String>['Hôm nay có gì đáng chú ý về Bitcoin?'],
      availability: ToolAvailability.partial,
    ),
    ToolDefinition(
      id: 'weather',
      name: 'Thời tiết',
      description: 'Thời tiết hiện tại và dự báo ngắn từ Open-Meteo.',
      category: ToolCategory.newsEnvironment,
      icon: Icons.wb_sunny_rounded,
      keywords: <String>['thời tiết', 'nhiệt độ', 'trời mưa', 'mưa không', 'bao nhiêu độ'],
      examples: <String>['Thời tiết Hà Nội hôm nay', 'Đà Nẵng có mưa không?'],
    ),
    ToolDefinition(
      id: 'air_quality',
      name: 'Chất lượng không khí',
      description: 'AQI, PM2.5 và PM10 theo vị trí từ Open-Meteo Air Quality.',
      category: ToolCategory.newsEnvironment,
      icon: Icons.air_rounded,
      keywords: <String>['aqi', 'chất lượng không khí', 'pm2.5', 'pm10', 'ô nhiễm không khí'],
      examples: <String>['AQI Hà Nội hiện tại', 'Không khí TP HCM hôm nay'],
    ),
    ToolDefinition(
      id: 'sports_score',
      name: 'Tỷ số thể thao',
      description: 'Tra đội bóng, kết quả gần nhất và lịch trận qua TheSportsDB.',
      category: ToolCategory.newsEnvironment,
      icon: Icons.sports_soccer_rounded,
      keywords: <String>['tỷ số', 'trận đấu', 'bóng đá', 'lịch thi đấu', 'kết quả trận', 'manchester united', 'arsenal'],
      examples: <String>['Tỷ số Manchester United', 'Lịch đấu Arsenal'],
      availability: ToolAvailability.partial,
    ),
  ];

  static ToolDefinition byId(String id) => all.firstWhere((item) => item.id == id);
}
